### ISSUE TITLE
kexec should be called with -a

### ISSUE THREAD

**Issue by jirislaby** [openSUSE/kdump#10]
When you invoke kexec, you let it use the old `kexec_load` syscall. This does not allow for signature verification of loaded images. You should pass -a to kexec to use `kexec_file_load` instead (and fall back to `kexec_load` if the former is not present).

**Comment by ptesarik** [comment]
Have you actually hit this issue in real world so that kdump `load.sh` fails where `kexec -a` succeeds?

I'm asking, because `kdump` first executes `kexec -s` and only if it fails, it retries with using the old `kexec_load` syscall. It is done that way for compatibility with older `kexec-tools` which did not have the `-a` switch.

**Comment by jirislaby** [comment]
Ah, in that case, everything should be alright. I hit a bug where kdump fails. Then I ran kexec -a manually to find the issue (the issue is fixed), but didn't notice kexec -s is called from kdump.
